
const Data=[
    {
        title:"Wakratund Mahakarya",
        img:"/img/5.jpg",
        content:"lorem25"
    }
    , {
        title:"Second blog",
        img:"/img/1.jpg",
        content: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Molestiae qui esse, optio quibusdam eum vitae! Tempore, exercitationem voluptatum. Distinctio tempore dolores atque odit aliquam impedit quae nobis dolor, vitae non neque corrupti molestiae consequatur cupiditate minus? Recusandae aspernatur, magnam praesentium inventore voluptatibus voluptatem incidunt consequuntur numquam tempora veritatis ut, cumque cum quisquam corrupti facere amet rerum nisi iure, ex cupiditate saepe. Consectetur quis amet mollitia? Nemo quos expedita eligendi quas nihil harum quod natus nisi. Distinctio fuga illum blanditiis expedita, animi incidunt maiores. A vero corporis, aspernatur quidem soluta dignissimos quas voluptatem tenetur, incidunt accusamus facere delectus asperiores dolorum dolor totam dolore animi blanditiis explicabo natus maxime fugiat voluptate ducimus provident! Quibusdam delectus ducimus nihil modi, ullam neque animi deserunt excepturi nam voluptates rem voluptate assumenda, dicta recusandae ipsum incidunt dolore architecto laborum? Quam, praesentium vitae dolor sint nulla eum omnis asperiores iure iste enim modi laboriosam deserunt soluta a consequuntur? Magni sit eum eius quos hic earum atque cum nihil vero adipisci exercitationem, neque saepe, omnis accusantium reprehenderit sunt nemo quasi dicta quod beatae illum modi possimus, praesentium tempore. Dignissimos sed sequi vero odio, temporibus atque commodi, quidem voluptatibus doloribus ad, quisquam inventore libero quo itaque. Perferendis cumque porro ratione excepturi ipsam libero explicabo. Odio voluptatem quibusdam aspernatur beatae, ea soluta harum nemo, temporibus inventore illum esse atque eum repellendus qui error. Soluta, ut quo? Quibusdam voluptatem odio dolor unde, debitis enim, ipsam maiores tempora hic non modi quos! Itaque quia, amet facilis ad asperiores iure architecto sequi? Aliquid."
    },
   
     {
        title:"Second blog",
        img:"/img/2.jpg",
        content: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Molestiae qui esse, optio quibusdam eum vitae! Tempore, exercitationem voluptatum. Distinctio tempore dolores atque odit aliquam impedit quae nobis dolor, vitae non neque corrupti molestiae consequatur cupiditate minus? Recusandae aspernatur, magnam praesentium inventore voluptatibus voluptatem incidunt consequuntur numquam tempora veritatis ut, cumque cum quisquam corrupti facere amet rerum nisi iure, ex cupiditate saepe. Consectetur quis amet mollitia? Nemo quos expedita eligendi quas nihil harum quod natus nisi. Distinctio fuga illum blanditiis expedita, animi incidunt maiores. A vero corporis, aspernatur quidem soluta dignissimos quas voluptatem tenetur, incidunt accusamus facere delectus asperiores dolorum dolor totam dolore animi blanditiis explicabo natus maxime fugiat voluptate ducimus provident! Quibusdam delectus ducimus nihil modi, ullam neque animi deserunt excepturi nam voluptates rem voluptate assumenda, dicta recusandae ipsum incidunt dolore architecto laborum? Quam, praesentium vitae dolor sint nulla eum omnis asperiores iure iste enim modi laboriosam deserunt soluta a consequuntur? Magni sit eum eius quos hic earum atque cum nihil vero adipisci exercitationem, neque saepe, omnis accusantium reprehenderit sunt nemo quasi dicta quod beatae illum modi possimus, praesentium tempore. Dignissimos sed sequi vero odio, temporibus atque commodi, quidem voluptatibus doloribus ad, quisquam inventore libero quo itaque. Perferendis cumque porro ratione excepturi ipsam libero explicabo. Odio voluptatem quibusdam aspernatur beatae, ea soluta harum nemo, temporibus inventore illum esse atque eum repellendus qui error. Soluta, ut quo? Quibusdam voluptatem odio dolor unde, debitis enim, ipsam maiores tempora hic non modi quos! Itaque quia, amet facilis ad asperiores iure architecto sequi? Aliquid."
    },
    
     {
        title:"Second blog",
        img:"/img/3.jpg",
        content: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Molestiae qui esse, optio quibusdam eum vitae! Tempore, exercitationem voluptatum. Distinctio tempore dolores atque odit aliquam impedit quae nobis dolor, vitae non neque corrupti molestiae consequatur cupiditate minus? Recusandae aspernatur, magnam praesentium inventore voluptatibus voluptatem incidunt consequuntur numquam tempora veritatis ut, cumque cum quisquam corrupti facere amet rerum nisi iure, ex cupiditate saepe. Consectetur quis amet mollitia? Nemo quos expedita eligendi quas nihil harum quod natus nisi. Distinctio fuga illum blanditiis expedita, animi incidunt maiores. A vero corporis, aspernatur quidem soluta dignissimos quas voluptatem tenetur, incidunt accusamus facere delectus asperiores dolorum dolor totam dolore animi blanditiis explicabo natus maxime fugiat voluptate ducimus provident! Quibusdam delectus ducimus nihil modi, ullam neque animi deserunt excepturi nam voluptates rem voluptate assumenda, dicta recusandae ipsum incidunt dolore architecto laborum? Quam, praesentium vitae dolor sint nulla eum omnis asperiores iure iste enim modi laboriosam deserunt soluta a consequuntur? Magni sit eum eius quos hic earum atque cum nihil vero adipisci exercitationem, neque saepe, omnis accusantium reprehenderit sunt nemo quasi dicta quod beatae illum modi possimus, praesentium tempore. Dignissimos sed sequi vero odio, temporibus atque commodi, quidem voluptatibus doloribus ad, quisquam inventore libero quo itaque. Perferendis cumque porro ratione excepturi ipsam libero explicabo. Odio voluptatem quibusdam aspernatur beatae, ea soluta harum nemo, temporibus inventore illum esse atque eum repellendus qui error. Soluta, ut quo? Quibusdam voluptatem odio dolor unde, debitis enim, ipsam maiores tempora hic non modi quos! Itaque quia, amet facilis ad asperiores iure architecto sequi? Aliquid."
    },
    {
        title:"Second blog",
        img:"/img/4.jpg",
        content: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Molestiae qui esse, optio quibusdam eum vitae! Tempore, exercitationem voluptatum. Distinctio tempore dolores atque odit aliquam impedit quae nobis dolor, vitae non neque corrupti molestiae consequatur cupiditate minus? Recusandae aspernatur, magnam praesentium inventore voluptatibus voluptatem incidunt consequuntur numquam tempora veritatis ut, cumque cum quisquam corrupti facere amet rerum nisi iure, ex cupiditate saepe. Consectetur quis amet mollitia? Nemo quos expedita eligendi quas nihil harum quod natus nisi. Distinctio fuga illum blanditiis expedita, animi incidunt maiores. A vero corporis, aspernatur quidem soluta dignissimos quas voluptatem tenetur, incidunt accusamus facere delectus asperiores dolorum dolor totam dolore animi blanditiis explicabo natus maxime fugiat voluptate ducimus provident! Quibusdam delectus ducimus nihil modi, ullam neque animi deserunt excepturi nam voluptates rem voluptate assumenda, dicta recusandae ipsum incidunt dolore architecto laborum? Quam, praesentium vitae dolor sint nulla eum omnis asperiores iure iste enim modi laboriosam deserunt soluta a consequuntur? Magni sit eum eius quos hic earum atque cum nihil vero adipisci exercitationem, neque saepe, omnis accusantium reprehenderit sunt nemo quasi dicta quod beatae illum modi possimus, praesentium tempore. Dignissimos sed sequi vero odio, temporibus atque commodi, quidem voluptatibus doloribus ad, quisquam inventore libero quo itaque. Perferendis cumque porro ratione excepturi ipsam libero explicabo. Odio voluptatem quibusdam aspernatur beatae, ea soluta harum nemo, temporibus inventore illum esse atque eum repellendus qui error. Soluta, ut quo? Quibusdam voluptatem odio dolor unde, debitis enim, ipsam maiores tempora hic non modi quos! Itaque quia, amet facilis ad asperiores iure architecto sequi? Aliquid."
    },
    {
        title:"Second blog",
        img:"/img/5.jpg",
        content: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Molestiae qui esse, optio quibusdam eum vitae! Tempore, exercitationem voluptatum. Distinctio tempore dolores atque odit aliquam impedit quae nobis dolor, vitae non neque corrupti molestiae consequatur cupiditate minus? Recusandae aspernatur, magnam praesentium inventore voluptatibus voluptatem incidunt consequuntur numquam tempora veritatis ut, cumque cum quisquam corrupti facere amet rerum nisi iure, ex cupiditate saepe. Consectetur quis amet mollitia? Nemo quos expedita eligendi quas nihil harum quod natus nisi. Distinctio fuga illum blanditiis expedita, animi incidunt maiores. A vero corporis, aspernatur quidem soluta dignissimos quas voluptatem tenetur, incidunt accusamus facere delectus asperiores dolorum dolor totam dolore animi blanditiis explicabo natus maxime fugiat voluptate ducimus provident! Quibusdam delectus ducimus nihil modi, ullam neque animi deserunt excepturi nam voluptates rem voluptate assumenda, dicta recusandae ipsum incidunt dolore architecto laborum? Quam, praesentium vitae dolor sint nulla eum omnis asperiores iure iste enim modi laboriosam deserunt soluta a consequuntur? Magni sit eum eius quos hic earum atque cum nihil vero adipisci exercitationem, neque saepe, omnis accusantium reprehenderit sunt nemo quasi dicta quod beatae illum modi possimus, praesentium tempore. Dignissimos sed sequi vero odio, temporibus atque commodi, quidem voluptatibus doloribus ad, quisquam inventore libero quo itaque. Perferendis cumque porro ratione excepturi ipsam libero explicabo. Odio voluptatem quibusdam aspernatur beatae, ea soluta harum nemo, temporibus inventore illum esse atque eum repellendus qui error. Soluta, ut quo? Quibusdam voluptatem odio dolor unde, debitis enim, ipsam maiores tempora hic non modi quos! Itaque quia, amet facilis ad asperiores iure architecto sequi? Aliquid."
    },
    {
        title:"Wakratund Mahakarya",
        img:"/img/5.jpg",
        content:"lorem25"
    }
    , {
        title:"Second blog",
        img:"/img/1.jpg",
        content: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Molestiae qui esse, optio quibusdam eum vitae! Tempore, exercitationem voluptatum. Distinctio tempore dolores atque odit aliquam impedit quae nobis dolor, vitae non neque corrupti molestiae consequatur cupiditate minus? Recusandae aspernatur, magnam praesentium inventore voluptatibus voluptatem incidunt consequuntur numquam tempora veritatis ut, cumque cum quisquam corrupti facere amet rerum nisi iure, ex cupiditate saepe. Consectetur quis amet mollitia? Nemo quos expedita eligendi quas nihil harum quod natus nisi. Distinctio fuga illum blanditiis expedita, animi incidunt maiores. A vero corporis, aspernatur quidem soluta dignissimos quas voluptatem tenetur, incidunt accusamus facere delectus asperiores dolorum dolor totam dolore animi blanditiis explicabo natus maxime fugiat voluptate ducimus provident! Quibusdam delectus ducimus nihil modi, ullam neque animi deserunt excepturi nam voluptates rem voluptate assumenda, dicta recusandae ipsum incidunt dolore architecto laborum? Quam, praesentium vitae dolor sint nulla eum omnis asperiores iure iste enim modi laboriosam deserunt soluta a consequuntur? Magni sit eum eius quos hic earum atque cum nihil vero adipisci exercitationem, neque saepe, omnis accusantium reprehenderit sunt nemo quasi dicta quod beatae illum modi possimus, praesentium tempore. Dignissimos sed sequi vero odio, temporibus atque commodi, quidem voluptatibus doloribus ad, quisquam inventore libero quo itaque. Perferendis cumque porro ratione excepturi ipsam libero explicabo. Odio voluptatem quibusdam aspernatur beatae, ea soluta harum nemo, temporibus inventore illum esse atque eum repellendus qui error. Soluta, ut quo? Quibusdam voluptatem odio dolor unde, debitis enim, ipsam maiores tempora hic non modi quos! Itaque quia, amet facilis ad asperiores iure architecto sequi? Aliquid."
    },
   
     {
        title:"Second blog",
        img:"/img/2.jpg",
        content: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Molestiae qui esse, optio quibusdam eum vitae! Tempore, exercitationem voluptatum. Distinctio tempore dolores atque odit aliquam impedit quae nobis dolor, vitae non neque corrupti molestiae consequatur cupiditate minus? Recusandae aspernatur, magnam praesentium inventore voluptatibus voluptatem incidunt consequuntur numquam tempora veritatis ut, cumque cum quisquam corrupti facere amet rerum nisi iure, ex cupiditate saepe. Consectetur quis amet mollitia? Nemo quos expedita eligendi quas nihil harum quod natus nisi. Distinctio fuga illum blanditiis expedita, animi incidunt maiores. A vero corporis, aspernatur quidem soluta dignissimos quas voluptatem tenetur, incidunt accusamus facere delectus asperiores dolorum dolor totam dolore animi blanditiis explicabo natus maxime fugiat voluptate ducimus provident! Quibusdam delectus ducimus nihil modi, ullam neque animi deserunt excepturi nam voluptates rem voluptate assumenda, dicta recusandae ipsum incidunt dolore architecto laborum? Quam, praesentium vitae dolor sint nulla eum omnis asperiores iure iste enim modi laboriosam deserunt soluta a consequuntur? Magni sit eum eius quos hic earum atque cum nihil vero adipisci exercitationem, neque saepe, omnis accusantium reprehenderit sunt nemo quasi dicta quod beatae illum modi possimus, praesentium tempore. Dignissimos sed sequi vero odio, temporibus atque commodi, quidem voluptatibus doloribus ad, quisquam inventore libero quo itaque. Perferendis cumque porro ratione excepturi ipsam libero explicabo. Odio voluptatem quibusdam aspernatur beatae, ea soluta harum nemo, temporibus inventore illum esse atque eum repellendus qui error. Soluta, ut quo? Quibusdam voluptatem odio dolor unde, debitis enim, ipsam maiores tempora hic non modi quos! Itaque quia, amet facilis ad asperiores iure architecto sequi? Aliquid."
    },
    
     {
        title:"Second blog",
        img:"/img/3.jpg",
        content: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Molestiae qui esse, optio quibusdam eum vitae! Tempore, exercitationem voluptatum. Distinctio tempore dolores atque odit aliquam impedit quae nobis dolor, vitae non neque corrupti molestiae consequatur cupiditate minus? Recusandae aspernatur, magnam praesentium inventore voluptatibus voluptatem incidunt consequuntur numquam tempora veritatis ut, cumque cum quisquam corrupti facere amet rerum nisi iure, ex cupiditate saepe. Consectetur quis amet mollitia? Nemo quos expedita eligendi quas nihil harum quod natus nisi. Distinctio fuga illum blanditiis expedita, animi incidunt maiores. A vero corporis, aspernatur quidem soluta dignissimos quas voluptatem tenetur, incidunt accusamus facere delectus asperiores dolorum dolor totam dolore animi blanditiis explicabo natus maxime fugiat voluptate ducimus provident! Quibusdam delectus ducimus nihil modi, ullam neque animi deserunt excepturi nam voluptates rem voluptate assumenda, dicta recusandae ipsum incidunt dolore architecto laborum? Quam, praesentium vitae dolor sint nulla eum omnis asperiores iure iste enim modi laboriosam deserunt soluta a consequuntur? Magni sit eum eius quos hic earum atque cum nihil vero adipisci exercitationem, neque saepe, omnis accusantium reprehenderit sunt nemo quasi dicta quod beatae illum modi possimus, praesentium tempore. Dignissimos sed sequi vero odio, temporibus atque commodi, quidem voluptatibus doloribus ad, quisquam inventore libero quo itaque. Perferendis cumque porro ratione excepturi ipsam libero explicabo. Odio voluptatem quibusdam aspernatur beatae, ea soluta harum nemo, temporibus inventore illum esse atque eum repellendus qui error. Soluta, ut quo? Quibusdam voluptatem odio dolor unde, debitis enim, ipsam maiores tempora hic non modi quos! Itaque quia, amet facilis ad asperiores iure architecto sequi? Aliquid."
    },
    {
        title:"Second blog",
        img:"/img/4.jpg",
        content: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Molestiae qui esse, optio quibusdam eum vitae! Tempore, exercitationem voluptatum. Distinctio tempore dolores atque odit aliquam impedit quae nobis dolor, vitae non neque corrupti molestiae consequatur cupiditate minus? Recusandae aspernatur, magnam praesentium inventore voluptatibus voluptatem incidunt consequuntur numquam tempora veritatis ut, cumque cum quisquam corrupti facere amet rerum nisi iure, ex cupiditate saepe. Consectetur quis amet mollitia? Nemo quos expedita eligendi quas nihil harum quod natus nisi. Distinctio fuga illum blanditiis expedita, animi incidunt maiores. A vero corporis, aspernatur quidem soluta dignissimos quas voluptatem tenetur, incidunt accusamus facere delectus asperiores dolorum dolor totam dolore animi blanditiis explicabo natus maxime fugiat voluptate ducimus provident! Quibusdam delectus ducimus nihil modi, ullam neque animi deserunt excepturi nam voluptates rem voluptate assumenda, dicta recusandae ipsum incidunt dolore architecto laborum? Quam, praesentium vitae dolor sint nulla eum omnis asperiores iure iste enim modi laboriosam deserunt soluta a consequuntur? Magni sit eum eius quos hic earum atque cum nihil vero adipisci exercitationem, neque saepe, omnis accusantium reprehenderit sunt nemo quasi dicta quod beatae illum modi possimus, praesentium tempore. Dignissimos sed sequi vero odio, temporibus atque commodi, quidem voluptatibus doloribus ad, quisquam inventore libero quo itaque. Perferendis cumque porro ratione excepturi ipsam libero explicabo. Odio voluptatem quibusdam aspernatur beatae, ea soluta harum nemo, temporibus inventore illum esse atque eum repellendus qui error. Soluta, ut quo? Quibusdam voluptatem odio dolor unde, debitis enim, ipsam maiores tempora hic non modi quos! Itaque quia, amet facilis ad asperiores iure architecto sequi? Aliquid."
    },
    {
        title:"Second blog",
        img:"/img/5.jpg",
        content: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Molestiae qui esse, optio quibusdam eum vitae! Tempore, exercitationem voluptatum. Distinctio tempore dolores atque odit aliquam impedit quae nobis dolor, vitae non neque corrupti molestiae consequatur cupiditate minus? Recusandae aspernatur, magnam praesentium inventore voluptatibus voluptatem incidunt consequuntur numquam tempora veritatis ut, cumque cum quisquam corrupti facere amet rerum nisi iure, ex cupiditate saepe. Consectetur quis amet mollitia? Nemo quos expedita eligendi quas nihil harum quod natus nisi. Distinctio fuga illum blanditiis expedita, animi incidunt maiores. A vero corporis, aspernatur quidem soluta dignissimos quas voluptatem tenetur, incidunt accusamus facere delectus asperiores dolorum dolor totam dolore animi blanditiis explicabo natus maxime fugiat voluptate ducimus provident! Quibusdam delectus ducimus nihil modi, ullam neque animi deserunt excepturi nam voluptates rem voluptate assumenda, dicta recusandae ipsum incidunt dolore architecto laborum? Quam, praesentium vitae dolor sint nulla eum omnis asperiores iure iste enim modi laboriosam deserunt soluta a consequuntur? Magni sit eum eius quos hic earum atque cum nihil vero adipisci exercitationem, neque saepe, omnis accusantium reprehenderit sunt nemo quasi dicta quod beatae illum modi possimus, praesentium tempore. Dignissimos sed sequi vero odio, temporibus atque commodi, quidem voluptatibus doloribus ad, quisquam inventore libero quo itaque. Perferendis cumque porro ratione excepturi ipsam libero explicabo. Odio voluptatem quibusdam aspernatur beatae, ea soluta harum nemo, temporibus inventore illum esse atque eum repellendus qui error. Soluta, ut quo? Quibusdam voluptatem odio dolor unde, debitis enim, ipsam maiores tempora hic non modi quos! Itaque quia, amet facilis ad asperiores iure architecto sequi? Aliquid."
    },
    {
        title:"Wakratund Mahakarya",
        img:"/img/5.jpg",
        content:"lorem25"
    }
    , {
        title:"Second blog",
        img:"/img/1.jpg",
        content: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Molestiae qui esse, optio quibusdam eum vitae! Tempore, exercitationem voluptatum. Distinctio tempore dolores atque odit aliquam impedit quae nobis dolor, vitae non neque corrupti molestiae consequatur cupiditate minus? Recusandae aspernatur, magnam praesentium inventore voluptatibus voluptatem incidunt consequuntur numquam tempora veritatis ut, cumque cum quisquam corrupti facere amet rerum nisi iure, ex cupiditate saepe. Consectetur quis amet mollitia? Nemo quos expedita eligendi quas nihil harum quod natus nisi. Distinctio fuga illum blanditiis expedita, animi incidunt maiores. A vero corporis, aspernatur quidem soluta dignissimos quas voluptatem tenetur, incidunt accusamus facere delectus asperiores dolorum dolor totam dolore animi blanditiis explicabo natus maxime fugiat voluptate ducimus provident! Quibusdam delectus ducimus nihil modi, ullam neque animi deserunt excepturi nam voluptates rem voluptate assumenda, dicta recusandae ipsum incidunt dolore architecto laborum? Quam, praesentium vitae dolor sint nulla eum omnis asperiores iure iste enim modi laboriosam deserunt soluta a consequuntur? Magni sit eum eius quos hic earum atque cum nihil vero adipisci exercitationem, neque saepe, omnis accusantium reprehenderit sunt nemo quasi dicta quod beatae illum modi possimus, praesentium tempore. Dignissimos sed sequi vero odio, temporibus atque commodi, quidem voluptatibus doloribus ad, quisquam inventore libero quo itaque. Perferendis cumque porro ratione excepturi ipsam libero explicabo. Odio voluptatem quibusdam aspernatur beatae, ea soluta harum nemo, temporibus inventore illum esse atque eum repellendus qui error. Soluta, ut quo? Quibusdam voluptatem odio dolor unde, debitis enim, ipsam maiores tempora hic non modi quos! Itaque quia, amet facilis ad asperiores iure architecto sequi? Aliquid."
    },
   
     {
        title:"Second blog",
        img:"/img/2.jpg",
        content: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Molestiae qui esse, optio quibusdam eum vitae! Tempore, exercitationem voluptatum. Distinctio tempore dolores atque odit aliquam impedit quae nobis dolor, vitae non neque corrupti molestiae consequatur cupiditate minus? Recusandae aspernatur, magnam praesentium inventore voluptatibus voluptatem incidunt consequuntur numquam tempora veritatis ut, cumque cum quisquam corrupti facere amet rerum nisi iure, ex cupiditate saepe. Consectetur quis amet mollitia? Nemo quos expedita eligendi quas nihil harum quod natus nisi. Distinctio fuga illum blanditiis expedita, animi incidunt maiores. A vero corporis, aspernatur quidem soluta dignissimos quas voluptatem tenetur, incidunt accusamus facere delectus asperiores dolorum dolor totam dolore animi blanditiis explicabo natus maxime fugiat voluptate ducimus provident! Quibusdam delectus ducimus nihil modi, ullam neque animi deserunt excepturi nam voluptates rem voluptate assumenda, dicta recusandae ipsum incidunt dolore architecto laborum? Quam, praesentium vitae dolor sint nulla eum omnis asperiores iure iste enim modi laboriosam deserunt soluta a consequuntur? Magni sit eum eius quos hic earum atque cum nihil vero adipisci exercitationem, neque saepe, omnis accusantium reprehenderit sunt nemo quasi dicta quod beatae illum modi possimus, praesentium tempore. Dignissimos sed sequi vero odio, temporibus atque commodi, quidem voluptatibus doloribus ad, quisquam inventore libero quo itaque. Perferendis cumque porro ratione excepturi ipsam libero explicabo. Odio voluptatem quibusdam aspernatur beatae, ea soluta harum nemo, temporibus inventore illum esse atque eum repellendus qui error. Soluta, ut quo? Quibusdam voluptatem odio dolor unde, debitis enim, ipsam maiores tempora hic non modi quos! Itaque quia, amet facilis ad asperiores iure architecto sequi? Aliquid."
    },
    
     {
        title:"Second blog",
        img:"/img/3.jpg",
        content: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Molestiae qui esse, optio quibusdam eum vitae! Tempore, exercitationem voluptatum. Distinctio tempore dolores atque odit aliquam impedit quae nobis dolor, vitae non neque corrupti molestiae consequatur cupiditate minus? Recusandae aspernatur, magnam praesentium inventore voluptatibus voluptatem incidunt consequuntur numquam tempora veritatis ut, cumque cum quisquam corrupti facere amet rerum nisi iure, ex cupiditate saepe. Consectetur quis amet mollitia? Nemo quos expedita eligendi quas nihil harum quod natus nisi. Distinctio fuga illum blanditiis expedita, animi incidunt maiores. A vero corporis, aspernatur quidem soluta dignissimos quas voluptatem tenetur, incidunt accusamus facere delectus asperiores dolorum dolor totam dolore animi blanditiis explicabo natus maxime fugiat voluptate ducimus provident! Quibusdam delectus ducimus nihil modi, ullam neque animi deserunt excepturi nam voluptates rem voluptate assumenda, dicta recusandae ipsum incidunt dolore architecto laborum? Quam, praesentium vitae dolor sint nulla eum omnis asperiores iure iste enim modi laboriosam deserunt soluta a consequuntur? Magni sit eum eius quos hic earum atque cum nihil vero adipisci exercitationem, neque saepe, omnis accusantium reprehenderit sunt nemo quasi dicta quod beatae illum modi possimus, praesentium tempore. Dignissimos sed sequi vero odio, temporibus atque commodi, quidem voluptatibus doloribus ad, quisquam inventore libero quo itaque. Perferendis cumque porro ratione excepturi ipsam libero explicabo. Odio voluptatem quibusdam aspernatur beatae, ea soluta harum nemo, temporibus inventore illum esse atque eum repellendus qui error. Soluta, ut quo? Quibusdam voluptatem odio dolor unde, debitis enim, ipsam maiores tempora hic non modi quos! Itaque quia, amet facilis ad asperiores iure architecto sequi? Aliquid."
    },
    {
        title:"Second blog",
        img:"/img/4.jpg",
        content: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Molestiae qui esse, optio quibusdam eum vitae! Tempore, exercitationem voluptatum. Distinctio tempore dolores atque odit aliquam impedit quae nobis dolor, vitae non neque corrupti molestiae consequatur cupiditate minus? Recusandae aspernatur, magnam praesentium inventore voluptatibus voluptatem incidunt consequuntur numquam tempora veritatis ut, cumque cum quisquam corrupti facere amet rerum nisi iure, ex cupiditate saepe. Consectetur quis amet mollitia? Nemo quos expedita eligendi quas nihil harum quod natus nisi. Distinctio fuga illum blanditiis expedita, animi incidunt maiores. A vero corporis, aspernatur quidem soluta dignissimos quas voluptatem tenetur, incidunt accusamus facere delectus asperiores dolorum dolor totam dolore animi blanditiis explicabo natus maxime fugiat voluptate ducimus provident! Quibusdam delectus ducimus nihil modi, ullam neque animi deserunt excepturi nam voluptates rem voluptate assumenda, dicta recusandae ipsum incidunt dolore architecto laborum? Quam, praesentium vitae dolor sint nulla eum omnis asperiores iure iste enim modi laboriosam deserunt soluta a consequuntur? Magni sit eum eius quos hic earum atque cum nihil vero adipisci exercitationem, neque saepe, omnis accusantium reprehenderit sunt nemo quasi dicta quod beatae illum modi possimus, praesentium tempore. Dignissimos sed sequi vero odio, temporibus atque commodi, quidem voluptatibus doloribus ad, quisquam inventore libero quo itaque. Perferendis cumque porro ratione excepturi ipsam libero explicabo. Odio voluptatem quibusdam aspernatur beatae, ea soluta harum nemo, temporibus inventore illum esse atque eum repellendus qui error. Soluta, ut quo? Quibusdam voluptatem odio dolor unde, debitis enim, ipsam maiores tempora hic non modi quos! Itaque quia, amet facilis ad asperiores iure architecto sequi? Aliquid."
    },
    {
        title:"Second blog",
        img:"/img/5.jpg",
        content: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Molestiae qui esse, optio quibusdam eum vitae! Tempore, exercitationem voluptatum. Distinctio tempore dolores atque odit aliquam impedit quae nobis dolor, vitae non neque corrupti molestiae consequatur cupiditate minus? Recusandae aspernatur, magnam praesentium inventore voluptatibus voluptatem incidunt consequuntur numquam tempora veritatis ut, cumque cum quisquam corrupti facere amet rerum nisi iure, ex cupiditate saepe. Consectetur quis amet mollitia? Nemo quos expedita eligendi quas nihil harum quod natus nisi. Distinctio fuga illum blanditiis expedita, animi incidunt maiores. A vero corporis, aspernatur quidem soluta dignissimos quas voluptatem tenetur, incidunt accusamus facere delectus asperiores dolorum dolor totam dolore animi blanditiis explicabo natus maxime fugiat voluptate ducimus provident! Quibusdam delectus ducimus nihil modi, ullam neque animi deserunt excepturi nam voluptates rem voluptate assumenda, dicta recusandae ipsum incidunt dolore architecto laborum? Quam, praesentium vitae dolor sint nulla eum omnis asperiores iure iste enim modi laboriosam deserunt soluta a consequuntur? Magni sit eum eius quos hic earum atque cum nihil vero adipisci exercitationem, neque saepe, omnis accusantium reprehenderit sunt nemo quasi dicta quod beatae illum modi possimus, praesentium tempore. Dignissimos sed sequi vero odio, temporibus atque commodi, quidem voluptatibus doloribus ad, quisquam inventore libero quo itaque. Perferendis cumque porro ratione excepturi ipsam libero explicabo. Odio voluptatem quibusdam aspernatur beatae, ea soluta harum nemo, temporibus inventore illum esse atque eum repellendus qui error. Soluta, ut quo? Quibusdam voluptatem odio dolor unde, debitis enim, ipsam maiores tempora hic non modi quos! Itaque quia, amet facilis ad asperiores iure architecto sequi? Aliquid."
    }
]



export default Data;
